name             'devbox'
maintainer       'Adam Edwards'
maintainer_email 'adamedx'
license          'All rights reserved'
description      'Installs/Configures devbox'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.2.0'
depends          'git'
depends          'chocolatey'
depends          'ruby_build'
depends          'build-essential'
